### ISSUE TITLE
Error occurred when using Battle Speed module on Chinese version of the game

### ISSUE THREAD

**Issue by YuiYuK1** [Z4ee/Pipsi-HSR-Releases#113]
![image](https://github.com/user-attachments/assets/698a064f-fffd-4d43-98aa-fa4c87fa15d1)
im on the latest version of pipsi(1.1.9)

**Comment by Z4ee** [comment]
what is the speed?
what were the numbers at the end of the battle? like 20/30 etc

**Comment by JustInfLOL** [comment]
> what is the speed? what were the numbers at the end of the battle? like 20/30 etc

i even tried 2.1 but it occured and the number is 2010

**Comment by Z4ee** [comment]
![image](https://github.com/user-attachments/assets/19294642-16bb-4669-bbb4-aa009cce3274)
I need these numbers

**Comment by Z4ee** [comment]
did you have them?

**Comment by JustInfLOL** [comment]
> did you have them?

actually i dont

**Comment by Z4ee** [comment]
try setting the speed to 100
and look you will have these numbers at the end of battle

**Comment by JustInfLOL** [comment]
nah it only occurs when the game's built-in battle speed is disabled (my fault) and there is still no number
when the game's battle speed is on it will be normal

**Comment by JustInfLOL** [comment]
the number went from 14/20 to 20/20 and the error occurs

**Comment by Z4ee** [comment]
but what if you turn off built-in battle speed at the beginning of the battle and then turn it on at the end?

**Comment by JustInfLOL** [comment]
it still occurs and the number went from 22/24 to 24/24

**Comment by Z4ee** [comment]
ok, they added more checking on the server

**Comment by Z4ee** [comment]
nah, i`d win
https://github.com/Z4ee/Pipsi-SR-Releases/releases/tag/1.2.0
